In [4]:
import numpy as np
import torch

# View == Reshape
t = np.array([[[0, 1, 2],
               [3, 4, 5]],

              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape) # == 총 12

print(ft.view([-1, 3])) # 앞에는 모르겠고 3개의 차원을 가질래
print(ft.view([-1, 3]).shape) # (2,2,3) --> (2x2, 3) == 총 12

print(ft.view([-1, 1, 3])) # 앞은 모르겠고 XX, 1, 3 의 모양을 가질래
print(ft.view([-1, 1, 3]).shape) # (2x2, 1, 3) == 총 12

torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [6]:
# Squeeze and Unsqueeze
# Squeeze 쥐어 짜자. = dimension의 element가 1인 경우에 그 demension을 없애준다.
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)
print('---------------------')
print(ft.squeeze())
print(ft.squeeze().shape)
print('---------------------')
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

print(ft.unsqueeze(0)) # the same as dim=0
print(ft.unsqueeze(0).shape)

print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

print(ft.unsqueeze(-1)) # the same as dim=1
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
---------------------
tensor([0., 1., 2.])
torch.Size([3])
---------------------
torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [14]:
lt = torch.LongTensor([[0], [1], [2], [0]])
print(lt)

one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 1)
print(one_hot)

print()
print('-------')
print('Casting')
print('-------')
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())

bt = torch.ByteTensor([True, False, False, True]) # boolean
print(bt)
print(bt.long())
print(bt.float())

print()
print('--------')
print('Stacking')
print('--------')
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))
print('--------')
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[0],
        [1],
        [2],
        [0]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])

-------
Casting
-------
tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])

--------
Stacking
--------
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
--------
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [9]:
# Concatenate --> Stacking으로 좀 더 편하게 사용 가능.
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [15]:
# Ones and Zeros
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)
print(torch.ones_like(x)) # x와 같은 shape의 행렬 생성
print(torch.zeros_like(x))
# ==> Device
print()
print('---')
print('Zip')
print('---')

for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])

---
Zip
---
1 4
2 5
3 6
1 4 7
2 5 8
3 6 9


In [18]:
# In-place Operation --> 속도 면에서 빠르지만, 크게 이점이 없을 수도 있다.
x = torch.FloatTensor([[1, 2], [3, 4]])

print(x.mul(2.))
print(x)
print('---')
print(x.mul_(2.)) # x에 연산값 저장.
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
---
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
