In [3]:
## Basic notation
## 2d tensor 
# |t| = (batch, dim) e.g. 64 x 256

## 3d tensor - vision
# |t| = (batch, width, height) --> a number of images
# pytorch -- (세로, 가로, 깊이) sequence

## 3d tensor - NLP(natural language processing)
# |t| = (batch, length, dim)
# 단면이 하나의 문장, batch size만큼 쌓여있다.

In [11]:
# NumPy Review - 1D Array with NumPy
import numpy as np
import torch

t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)
print('Rank of t: ', t.ndim) # 몇개의 차원
print('Shape of t: ', t.shape) # 하나의 차원은 어떻게 있니
print('t[0] t[1] t[-1] = ', t[0],t[1],t[-1]) # -1인덱스는 맨 마지막에서 첫번쨰
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1])
print('t[:2] t[3:] = ', t[:2], t[3:])

[0. 1. 2. 3. 4. 5. 6.]
Rank of t:  1
Shape of t:  (7,)
t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:] =  [0. 1.] [3. 4. 5. 6.]


In [12]:
# NumPy Review - 2D Array with NumPy
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)
print(t.ndim)  # rank
print(t.shape) # shape

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
2
(4, 3)


In [13]:
# PyTorch is just like NumPy - 1D
t = np.array([0., 1., 2., 3., 4., 5., 6.])
ft = torch.FloatTensor(t)
print(ft)
print(ft.dim())  # rank
print(ft.shape)  # shape
print(ft.size()) # shape
print(ft[0], ft[1], ft[-1]) # Element
print(ft[2:5], ft[4:-1])    # Slicing
print(ft[:2], ft[3:])       # Slicing

tensor([0., 1., 2., 3., 4., 5., 6.])
1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [18]:
# PyTorch is just like NumPy - 2D
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
ft = torch.FloatTensor(t)
print(ft)
print(ft.dim())  # rank
print(ft.size()) # shape
print(ft[:, 1])
print(ft[:, 1].size())
print(ft[:, :-1])

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])
2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [22]:
## Broadcasting
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)
print('---------')
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3 -> [[3, 3]] -- 크기를 자동으로 바꿔서 연산 수행.
print(m1 + m2)
print('---------')
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]]) # 2x2 로 변환해서 두개를 덧셈 연산함.
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[5., 5.]])
---------
tensor([[4., 5.]])
---------
tensor([[4., 5.],
        [5., 6.]])


In [24]:
##'Mul vs Matmul'
# Deep learning은 행렬 곱을 많이 사용함.
# 
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1
print('---------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
---------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [25]:
# Mean
t = torch.FloatTensor([1, 2])
print(t.mean())

# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)
    
print('---------')
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.mean()) # 전체 평균
print(t.mean(dim=0)) # 
print(t.mean(dim=1))
print(t.mean(dim=-1))

tensor(1.5000)
Can only calculate the mean of floating types. Got Long instead.
---------
tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [26]:
# Sum
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [28]:
# Max and Argmax
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print('---------')
print(t.max()) # Returns one value: max
print(t.max(dim=0)) # Returns two values: max and argmax
print('Max: ', t.max(dim=0)[0]) # value
print('Argmax: ', t.max(dim=0)[1]) # index 
print('---------')
print(t.max(dim=1))
print(t.max(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
---------
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])
---------
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
